#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
export GOPATH=$HOME/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
source virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
export CATALINA_HOME=/usr/share/tomcat7

alias ff='find . -iname $@'
alias fp="fzf --preview 'pygmentize -g  {} 2> /dev/null '"
alias vp="vim \`fp\`"


# zsh
alias vim="stty stop '' -ixoff ; vim"
# `Frozing' tty, so after any command terminal settings will be restored
ttyctl -f

autoload -Uz promptinit
    promptinit
    prompt skwp

fpath=(/usr/local/share/zsh-completions $fpath)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
