#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
PYPATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin
JSPATH=$HOME/.yarn
export GOPATH=$HOME/go
export PATH=$PYPATH:$JSPATH/bin:$GOPATH/bin:$PATH
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export JAVA_HOME=/usr/lib/jvm/default-java

alias ff='find . -iname $@'
alias fp="fzf --preview 'pygmentize -g  {} 2> /dev/null '"
alias vp="vim \`fp\`"

if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi


# zsh
alias vim="stty stop '' -ixoff ; vim"
# `Frozing' tty, so after any command terminal settings will be restored
ttyctl -f

autoload -Uz promptinit
    promptinit
    prompt skwp

fpath=(/usr/local/share/zsh-completions $fpath)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

