#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GOPATH=$HOME/go
export GOROOT=$HOME/myapps/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
source /usr/local/bin/virtualenvwrapper.sh

